# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    import.csv:
        class: AppBundle\Service\ImportService
        arguments: ["@doctrine.orm.entity_manager", "@validator","@helper.utility" ]

    helper.utility:
        class: AppBundle\Utility\HelperUtility
        arguments: ["@validator","@doctrine.orm.entity_manager"]
